name: vdev20210801
description: Vdev Assignment.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-ExtraBold.ttf
        - asset: assets/font/Poppins-ExtraLight.ttf
        - asset: assets/font/Poppins-Light.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-Thin.ttf
